config/routes.rb
Rails.application.routes.draw do
  get 'movies', to: 'movies#index'
  get 'movies/new'
  post 'movies', to: 'movies#create'
  get 'movies/:id', to: 'movies#show', as: 'show'
  get 'movies/:id/edit', to: 'movies#edit', as: 'edit_movie'
  patch 'movies/:id', to: 'movies#update', as: :movie
  delete 'movies/:id', to: 'movies#delete'
  patch 'favorite_movies/:id', to: 'favorite_movies#update', as: 'favorite_movie'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/favorite_movies_controller.rb
class FavoriteMoviesController < ApplicationController
  before_action :movie_find, only: [:update]
  def update
    if @movie.favorite?
    @movie.favorite = false
    @movie.save
    redirect_to movies_path, notice: 'Película agregada de favoritos'
    else
    @movie.favorite = true
    @movie.save
    redirect_to movies_path, notice: 'Película eliminada de favoritos'
    end
  end

  private
  def movie_find
    @movie = Movie.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :movie_find, only: [:show, :edit, :update, :delete, :favorite]

  def index
    @regular_movies = Movie.where(favorite: false)
    @favorite_movies = Movie.where(favorite: true)
  end


  def new; end

  def create
    @new_movie = Movie.new(movies_params)
    @new_movie.save
    redirect_to movies_path
  end

  def show; end

  def edit; end

  def update
    @movie.update(movies_params)
    redirect_to movies_path
  end

  def delete
    @movie.destroy
    redirect_to movies_path
  end

  private
  def movies_params
    params.require(:movie).permit(:name, :year)
  end

  def movie_find
    @movie = Movie.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorite_movies_helper.rb
module FavoriteMoviesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movies</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'Movie', movies_path, class: 'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <div class="navbar-nav">
        <div class="nav-item active">
          <%= link_to 'Movies', movies_path, class:'nav-link' %>
        </div>
        <div class="nav-item">
          <%= link_to 'New Movie', movies_new_path, class:'nav-link' %>
        </div>
        <div class="nav-item">
        <div class="nav-link"><%= notice %></div>
        </div>
      </div>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with model: movie, local: true do |f| %>
  <%= f.label 'Movie Name' %>
  <%= f.text_field :name %>

  <%= f.label 'Movie Year' %>
  <%= f.number_field :year %>

  <%= f.submit 'Submit Movie' %>
<% end %>

app/views/movies/edit.html.erb
<h1> Edit Movie </h1>

<%= render 'form', movie: @movie %>

<%= link_to '<<Back', movies_path, class: 'btn btn-warning' %>

app/views/movies/index.html.erb
<br>
<div class="container">

  <% if @favorite_movies.count > 0 %>
    <h1 class="card text-center"> Favorite Movies</h1>
  <table class="table">
    <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Year</th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @favorite_movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
        <td><%= movie.year %></td>
        <td>
          <div class="dropdown">
            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              ...
            </a>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <%= link_to 'Edit', edit_movie_path(movie), class: 'dropdown-item'  %>
              <%= link_to 'Show', movie, class: 'dropdown-item' %>
              <%= link_to 'Delete', movie, method: :delete, data: {confirm: 'Are you sure?!'}, class: 'dropdown-item' %>
              <%= button_to 'Delete Favorite', favorite_movie_path(movie), method: :patch, class: 'dropdown-item' %>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<%end %>
  <h1 class="card text-center"> Regular Movies</h1>
  <table class="table">
    <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Year</th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @regular_movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
        <td><%= movie.year %></td>
        <td>
          <div class="dropdown">
          <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            ...
          </a>

          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <%= link_to 'Edit', edit_movie_path(movie), class: 'dropdown-item'  %>
            <%= link_to 'Show', movie, class: 'dropdown-item' %>
            <%= link_to 'Delete', movie, method: :delete, data: {confirm: 'Are you sure?!'}, class: 'dropdown-item' %>
            <%= button_to 'Add Favorite', favorite_movie_path(movie), method: :patch, class: 'dropdown-item' %>
          </div>
        </div>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/movies/new.html.erb
<h1> New Movie</h1>

<%= render 'form', movie: Movie.new %>

<%= link_to '<< Back', movies_path, class: 'btn btn-warning'  %>

app/views/movies/show.html.erb
<%= @movie.name %>
<%= @movie.year %>
<%= link_to '<<Back', movies_path, class: 'btn btn-warning'  %>
<%= link_to 'Edit', edit_movie_path(@movie), class: 'btn btn-warning'  %>